fix: use target OS tag for TLS library linking in cross-compilation
When cross-compiling from macOS to Linux musl target, the build system
was incorrectly using builtin.os.tag (host OS) instead of
target.result.os_tag (target OS) to determine which TLS libraries to link.

This caused the build to fail with:
  error: unable to find dynamic system library 'z'
  error: unable to find dynamic system library 'ssl'
  error: unable to find dynamic system library 'crypto'

Fixed by changing the link logic in build.zig to use target.result.os_tag
for all three linking locations (exe, lib_tests, exe_tests).